### ISSUE TITLE
bitbucket_group import crashes

### ISSUE THREAD

**Issue by mariusz-zalewski-tech** [zahiar/terraform-provider-bitbucket#72]
**Terraform version**

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/zahiar/bitbucket v1.0.0
```

**Affected resource(s)**

    bitbucket_group

**Expected Behavior**

Import that resource without errors

**Actual Behavior**

```
$ cat groups.tf 
resource "bitbucket_group" "iac_read" {
  workspace  = data.bitbucket_workspace.this.uuid
  name       = "IaC_Read"
  auto_add   = false
}

$ tf import bitbucket_group.iac_read "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}/IaC_Read"
bitbucket_group.iac_read: Importing from ID "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}/IaC_Read"...
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).ImportResourceState request was cancelled.
╵


Stack trace from the terraform-provider-bitbucket_v1.0.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 65 [running]:
github.com/zahiar/terraform-provider-bitbucket/bitbucket/api/v1.(*Groups).Get(0xc000364570, 0xc0003d37c8, 0x4, 0x1816e80, 0xc0006189e0)
        github.com/zahiar/terraform-provider-bitbucket/bitbucket/api/v1/groups.go:61 +0x545
github.com/zahiar/terraform-provider-bitbucket/bitbucket.resourceBitbucketGroupRead(0x1a3e800, 0xc000056600, 0xc000477400, 0x17f33c0, 0xc000470f80, 0x0, 0x0, 0x2)
        github.com/zahiar/terraform-provider-bitbucket/bitbucket/resource_bitbucket_group.go:84 +0x169
github.com/zahiar/terraform-provider-bitbucket/bitbucket.resourceBitbucketGroupImport(0x1a3e800, 0xc000056600, 0xc000477400, 0x17f33c0, 0xc000470f80, 0xc0005a2201, 0x1499db2, 0xc000580480, 0x0, 0x0)
        github.com/zahiar/terraform-provider-bitbucket/bitbucket/resource_bitbucket_group.go:153 +0x23a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc00007e2a0, 0x1a3e800, 0xc000056600, 0xc0003d3a28, 0xc0001343f0, 0x2f, 0xc000477180, 0xc000132170, 0x9, 0xc000000001, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/provider.go:382 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc00000c1c0, 0x1a3e800, 0xc000056600, 0xc000262940, 0x19466ad, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1043 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc00039a280, 0x1a3e800, 0xc000056600, 0xc00057a0f0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:628 +0x2f2
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler(0x1908c80, 0xc00039a280, 0x1a3e8c0, 0xc0001107b0, 0xc0003865a0, 0x0, 0x1a3e8c0, 0xc0001107b0, 0xc0003800f0, 0x42)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:398 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ac700, 0x1a46600, 0xc000390a80, 0xc00018a000, 0xc0003826c0, 0x1ebc3f8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0000ac700, 0x1a46600, 0xc000390a80, 0xc00018a000, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000362a0, 0xc0000ac700, 0x1a46600, 0xc000390a80, 0xc00018a000)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-bitbucket_v1.0.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by zahiar** [comment]
@mariusz-zalewski-tech Thanks for the bug report. Looks like the API didn't return any groups hence the error `index out of range [0] with length 0`

I'll put a pull request up shortly to more gracefully handle this.

Things I can think of that may be causing this issue for you are:
- Does your user have the correct permissions to access the group you are trying to import?
- Is this `IaC_Read` definitely the group slug? Generally it tends to be all lower-case.
Try going to the `IaC_Read` groups page in Bitbucket and look at the URL, the last part will be the group slug, for example: `https://bitbucket.org/user_name/workspace/settings/groups/iac_read`

**Comment by zahiar** [comment]
Further update: I created a group named `TF-BB-Group-Test` and it did fail during the import when I used the group's name `TF-BB-Group-Test`, if I used the slug which was `tf-bb-group-test`, it then worked correctly. I'm more confident that is perhaps your issue 🙂
